# Common settings
title: Ria Carmin | UX UI Designer 
description:  I am a product designer. I strive to create great interfaces for people, on any screen or device. I focus on new innovative approaches to web and mobile UI.
url: http://loveux.co

sass:
  style: compressed

# Build settings
markdown: kramdown
